"""Revision for users table: added a new field (deleted)

Revision ID: ef70300e3fa0
Revises: 3cb292f6a848
Create Date: 2025-11-10 06:04:05.963909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ef70300e3fa0"
down_revision: Union[str, Sequence[str], None] = "3cb292f6a848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted")
    # ### end Alembic commands ###
