"""Revision to add deleted to attribute to both products and categories

Revision ID: f62d90b736bd
Revises: 324060a32916
Create Date: 2025-11-10 13:31:43.391785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f62d90b736bd'
down_revision: Union[str, Sequence[str], None] = '324060a32916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted')
    op.drop_column('categories', 'deleted')
    # ### end Alembic commands ###
